#!/usr/bin/env bash

set -e # exit on any error

# pull in dotbot dependencies
(cd "${DOTBOT_DIR}" && git submodule update --init --recursive --quiet)

# run dotbot
dotbot/bin/dotbot -c "setup.yaml" "${@}"
