#!/usr/bin/env bash

# echo "Enter password to grant sudo access during installation:"
# sudo -v

# pull in dotbot dependencies
(cd dotbot && git submodule update --init --recursive --quiet)

# run dotbot
dotbot/bin/dotbot -c "setup.yaml" "${@}"
