# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$hostname\
$sudo\
$cmd_duration\
$fill\
$username\
$rust\
$python\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$custom\

$line_break\
$jobs\
$battery\
$status\
$container\
$shell\
$character"""

[fill]
symbol = " "

[cmd_duration]
format = '[ $duration]($style) '
style = "bright-black"

[sudo]
format = "[\\(as sudo\\)]($style)"
disabled = false

[hostname]
ssh_only = true
format = '[| $hostname](bright-white) '

[username]
disabled = true
show_always = true
format = '[ $user | ](bright-white)'

# --------- #
# LANGUAGES #
# --------- #

[python]
format = '[ ${version} $virtualenv | ](bright-white)'
detect_extensions = []
detect_files = []
detect_folders = []
version_format = '$v${major}.${minor}'

[rust]
format = '[ ${version} | ](bright-white)'
version_format = '$v${major}.${minor}'

# --- #
# GIT #
# --- #

[git_branch]
format = "[ $branch ](bright-white)"

[git_status]
format = '[$conflicted$stashed$deleted$renamed$typechanged$staged$untracked$ahead_behind](red) '

[git_metrics]
format = '([+$added](green) )([-$deleted](red) )[|](bright-white) '
ignore_submodules = true
disabled = false

# ------ #
# CUSTOM #
# ------ #
[custom.system_icons]
command = "echo $(uname -s | tr '[:upper:]' '[:lower:]' | sed 's/darwin//g' | sed 's/linux/󰌽/g')"
format = "[$output]($style) "
style = "bright-white"
shell = ["bash", "--noprofile", "--norc"]
when = "true"
