{ config, ... }:
let
  inherit (config.lib.dotfiles) link;
in
{
  programs.git = {
    enable = true;
    lfs.enable = true;
    settings = {
      user = {
        name = "Alistair Pattison";
        email = "alistairpattison@gmail.com";
      };

      init = {
        defaultBranch = "main";
        templatedir = "~/.git/templates";
      };
      push = {
        autoSetupRemote = true;
        followTags = true;
      };
      pull.rebase = "merges";
    };

    # written to ~/.config/git/ignore, which git reads by default
    ignores = [
      ".DS_Store"
      "*.local.*"
      "**/.claude/.cc-writes/"
      "**/.claude/settings.local.json"
    ];
  };

  # also registers gh as git's credential helper for github. auth state lives
  # in ~/.config/gh/hosts.yml, written by `gh auth login`
  programs.gh = {
    enable = true;
    settings = {
      git_protocol = "https";
      prompt = "enabled";
      aliases.co = "pr checkout";
    };
  };

  # config and ignore file are generated by programs.git above
  home.file.".git/templates".source = link "git/templates";
}
