{ pkgs, ... }:

{
  imports = [
    # generated by nixos-generate-config; copy from /etc/nixos/hardware-configuration.nix
    ./hardware.nix
    # ./nas.nix # TODO: fix this (currently breaks system)
  ];

  nixpkgs.hostPlatform = "x86_64-linux";

  nix = {
    # nixos-rebuild enables flakes for itself only; nix run and direnv need this
    settings.experimental-features = [
      "nix-command"
      "flakes"
    ];
    settings.trusted-users = [ "ali" ];
    gc.automatic = true;
    gc.options = "--delete-older-than 30d";
    optimise.automatic = true;
  };

  # bootloader
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.systemd-boot.enable = true;

  # networking
  networking.hostName = "fridge";
  networking.networkmanager.enable = true;

  # firewall
  networking.firewall = {
    enable = true;
    trustedInterfaces = [ "tailscale0" ];
  };

  # tailscale
  services.tailscale = {
    enable = true;
    useRoutingFeatures = "both";
    extraSetFlags = [ "--ssh" ];
  };
  # https://github.com/alipatti/bot (docker compose stack, cloned to ~/projects/bot)
  systemd.services.bot = {
    description = "alipatti-bot docker compose stack";
    wantedBy = [ "multi-user.target" ];
    after = [ "docker.service" ];
    requires = [ "docker.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      WorkingDirectory = "/home/ali/projects/bot";
      ExecStart = "${pkgs.docker}/bin/docker compose --env-file secrets.env up -d --build";
      ExecStop = "${pkgs.docker}/bin/docker compose --env-file secrets.env down";
      TimeoutStartSec = "20min"; # image build can take a while
    };
  };

  # TODO: setup nginx reverse proxy

  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";

  # graphics
  hardware.graphics.enable = true;
  hardware.nvidia = {
    open = true; # recommended for Turing onwards
    powerManagement.enable = true; # fixes broken graphics after sleep
  };
  services.xserver.videoDrivers = [ "nvidia" ];

  # gdm/gnome
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;
  services.gnome.core-apps.enable = false;
  services.gnome.core-developer-tools.enable = false;
  services.gnome.games.enable = false;
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour
    gnome-user-docs
  ];

  # misc
  programs.nix-ld.enable = true; # needed for uv
  programs.fish.enable = true;
  virtualisation.docker.enable = true;
  programs.steam.enable = true;

  # the rest of the desktop is user config in ../../home/linux.nix
  environment.systemPackages = with pkgs; [
    nautilus
    gnomeExtensions.appindicator # systray support for gnome
  ];

  users.users.ali = {
    isNormalUser = true;
    shell = pkgs.fish;
    extraGroups = [
      "networkmanager" # allow network config
      "wheel" # allow sudo
      "docker"
    ];
  };
  system.stateVersion = "25.11"; # don't change this line
}
