#!/bin/sh
/Applications/kitty.app/Contents/MacOS/kitty \
	--instance-group floating \
	--directory ~ \
	-o hide_window_decorations=titlebar-only \
	-o remember_window_size=no \
	-o initial_window_width=120c \
	-o initial_window_height=40c \
	-o window_padding_width=15 \
	-o macos_window_resizable=no \
	-o macos_hide_from_tasks=yes \

