#!/bin/bash

/Applications/kitty.app/Contents/MacOS/kitty \
    --directory ~ \
    --title FloatingKittyWindow \
    -o hide_window_decorations=titlebar-only \
    -o macos_window_resizable=no \
    -o background_opacity=0.95 \
    -o background_blur=5 \
    -o tab_bar_style=hidden \
    -o macos_hide_from_tasks=yes

