# claude code and codex. claude's settings.json is generated by
# programs.claude-code; the rest of ~/.claude is runtime state claude owns

{ config, ... }:
let
  inherit (config.lib.dotfiles) root link;

  # hosts claude code may reach, both from the sandbox and through WebFetch
  allowedDomains = [
    "pypi.org"
    "files.pythonhosted.org"
    "github.com"
    "api.github.com"
    "raw.githubusercontent.com"
    "objects.githubusercontent.com"
    "anthropic.com"
    "api.anthropic.com"
    "docs.anthropic.com"
    "crates.io"
    "static.crates.io"
    "docs.pola.rs"
    "pola.rs"
    "neovim.io"
    "json.schemastore.org"
    "schemastore.org"
  ];
in
{
  # ~/.claude/settings.json is generated from this. claude code cannot write
  # to it, so toggles made through /config or /plugin have to be added here
  programs.claude-code = {
    enable = true;
    settings = {
      model = "claude-fable-5-1[1m]";
      effortLevel = "medium";
      theme = "dark-ansi";
      tui = "fullscreen";

      permissions = {
        defaultMode = "auto";
        allow = map (d: "WebFetch(domain:${d})") allowedDomains;
      };

      sandbox = {
        enabled = true;
        network.allowedDomains = allowedDomains;
        filesystem.allowWrite = [ "~/.cache/uv/" ];
      };

      hooks.PostToolUse = [
        {
          matcher = "Edit|MultiEdit|Write|Bash";
          hooks = [
            {
              type = "command";
              # reload buffers when claude runs inside nvim's terminal
              command = ''[ -n "$NVIM" ] && nvim --server "$NVIM" --remote-send '<cmd>checktime<cr>' || true'';
            }
          ];
        }
      ];

      statusLine = {
        type = "command";
        command = "${root}/tools/claude_prompt.py";
      };

      enabledPlugins = {
        "github@claude-plugins-official" = true;
        "pyright-lsp@claude-plugins-official" = true;
        "lua-lsp@claude-plugins-official" = true;
      };

      # notifications
      preferredNotifChannel = "notifications_disabled";
      inputNeededNotifEnabled = true;
      agentPushNotifEnabled = true;
      awaySummaryEnabled = false;

      autoCompactEnabled = true;
      skipWorkflowUsageWarning = true;

      # kitty sets the tab title itself
      env.CLAUDE_CODE_DISABLE_TERMINAL_TITLE = "1";
    };
  };

  programs.codex.enable = true;

  home.file = {
    ".claude/CLAUDE.md".source = link "home/agents.md";
    ".claude/skills".source = link "skills";
    ".codex/AGENTS.md".source = link "home/agents.md";
    ".codex/skills".source = link "skills";
  };
}
