# claude code and codex. claude's settings.json is generated by
# programs.claude-code; the rest of ~/.claude is runtime state claude owns

{ config, ... }:
let
  inherit (config.lib.dotfiles) root link;

  # hosts claude code may reach, both from the sandbox and through WebFetch
  allowedDomains = [
    "pypi.org"
    "files.pythonhosted.org"
    "github.com"
    "api.github.com"
    "raw.githubusercontent.com"
    "objects.githubusercontent.com"
    "anthropic.com"
    "api.anthropic.com"
    "docs.anthropic.com"
    "crates.io"
    "static.crates.io"
    "docs.pola.rs"
    "pola.rs"
    "neovim.io"
    "json.schemastore.org"
    "schemastore.org"
    # canvas api, then the hosts file downloads redirect through and
    # submissions upload to
    "princeton.instructure.com"
    "*.canvas-user-content.com"
    "*.inscloudgate.net"
  ];
in
{
  # ~/.claude/settings.json is generated from this. claude code cannot write
  # to it, so toggles made through /config or /plugin have to be added here
  programs.claude-code = {
    enable = true;
    settings = {
      model = "claude-opus-5-5[1m]";
      effortLevel = "medium";
      theme = "dark-ansi";
      tui = "fullscreen";
      # don't auto-open the diff panel on the right; /diff still toggles it
      diffSidebarOpen = false;
      # skills come from ./skills; don't pull claude.ai's into it
      syncClaudeAiSkills = false;

      permissions = {
        defaultMode = "auto";
        allow = map (d: "WebFetch(domain:${d})") allowedDomains;
        # local history is fair game (the reflog keeps it recoverable) but
        # pushed history isn't. deny rules are checked before the sandbox
        # auto-allow; --force also covers --force-with-lease
        deny = map (c: "Bash(git ${c})") [
          "push*--force*"
          "push* -f*"
          "push* +*"
        ];
      };

      sandbox = {
        enabled = true;
        network.allowedDomains = allowedDomains;
        # uv keeps managed pythons and tools in ~/.local/share/uv and writes
        # temp files there even for `uv run`
        filesystem.allowWrite = [
          "~/.cache/"
          "~/.local/share/uv/"
        ];
      };

      hooks.PostToolUse = [
        {
          matcher = "Edit|MultiEdit|Write|Bash";
          hooks = [
            {
              type = "command";
              # reload buffers when claude runs inside nvim's terminal
              command = ''[ -n "$NVIM" ] && nvim --server "$NVIM" --remote-send '<cmd>checktime<cr>' || true'';
            }
          ];
        }
      ];

      statusLine = {
        type = "command";
        command = "${root}/tools/claude_prompt.py";
      };

      enabledPlugins = {
        "github@claude-plugins-official" = true;
        "lua-lsp@claude-plugins-official" = true;
      };

      # notifications
      preferredNotifChannel = "notifications_disabled";
      inputNeededNotifEnabled = true;
      agentPushNotifEnabled = true;
      awaySummaryEnabled = false;

      # no co-authored-by trailer on commits or footer on prs
      attribution = {
        commit = "";
        pr = "";
      };

      # lessons go in claude.md files, skills, or config instead (see ./agents.md)
      autoMemoryEnabled = false;
      autoCompactEnabled = true;
      skipWorkflowUsageWarning = true;

      # kitty sets the tab title itself
      env.CLAUDE_CODE_DISABLE_TERMINAL_TITLE = "1";
      # nvim's default log dir isn't writable in the sandbox, so it falls
      # back to ./nvim.log in whatever directory it was run from
      env.NVIM_LOG_FILE = "/tmp/claude/nvim.log";
    };
  };

  programs.codex.enable = true;

  home.file = {
    ".claude/CLAUDE.md".source = link "home/modules/agents.md";
    ".claude/skills".source = link "skills";
    # enter inserts a newline and ctrl+enter takes over enter's default
    # submit, which queues mid-turn instead of interrupting like sendNow
    ".claude/keybindings.json".text = builtins.toJSON {
      "$schema" = "https://www.schemastore.org/claude-code-keybindings.json";
      "$docs" = "https://code.claude.com/docs/en/keybindings";
      bindings = [
        {
          context = "Chat";
          bindings = {
            enter = "chat:newline";
            "ctrl+enter" = "chat:submit";
          };
        }
      ];
    };
    ".codex/AGENTS.md".source = link "home/modules/agents.md";
    ".codex/skills".source = link "skills";
  };
}
