# claude code and codex. claude's settings.json is generated by
# programs.claude-code; the rest of ~/.claude is runtime state claude owns

{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (config.lib.dotfiles) root link;

  # hosts claude code may reach, both from the sandbox and through WebFetch
  allowedDomains = [
    "pypi.org"
    "files.pythonhosted.org"
    "github.com"
    "api.github.com"
    "raw.githubusercontent.com"
    "objects.githubusercontent.com"
    "anthropic.com"
    "api.anthropic.com"
    "docs.anthropic.com"
    "crates.io"
    "static.crates.io"
    "docs.pola.rs"
    "pola.rs"
    "neovim.io"
    "json.schemastore.org"
    "schemastore.org"
    # canvas api, then the hosts file downloads redirect through and
    # submissions upload to
    "princeton.instructure.com"
    "*.canvas-user-content.com"
    "*.inscloudgate.net"
  ];
in
{
  # the tab title comes from fish_title (see tools/kitty_tab_bar.py). set in
  # the shell: with it in settings.json's env, claude still retitled tabs
  # (that env seems to be applied after claude reads the flag)
  home.sessionVariables.CLAUDE_CODE_DISABLE_TERMINAL_TITLE = "1";

  # ~/.claude/settings.json is generated from this. claude code cannot write
  # to it, so toggles made through /config or /plugin have to be added here
  programs.claude-code = {
    enable = true;
    settings = {
      model = "claude-opus-5-5[1m]";
      effortLevel = "medium";
      theme = "dark-ansi";
      tui = "fullscreen";
      # don't auto-open the diff panel on the right; /diff still toggles it
      diffSidebarOpen = false;
      # skills come from ./skills; don't pull claude.ai's into it
      syncClaudeAiSkills = false;

      permissions = {
        defaultMode = "auto";
        allow = map (d: "WebFetch(domain:${d})") allowedDomains ++ [
          # runs unsandboxed (see sandbox.excludedCommands)
          "Bash(pdf2md:*)"
        ];
        # local history is fair game (the reflog keeps it recoverable) but
        # pushed history isn't. deny rules are checked before the sandbox
        # auto-allow; --force also covers --force-with-lease
        deny = map (c: "Bash(git ${c})") [
          "push*--force*"
          "push* -f*"
          "push* +*"
        ];
      };

      sandbox = {
        enabled = true;
        network.allowedDomains = allowedDomains;
        # pdf2md talks to a local llama-server and nests codex's own
        # sandbox, neither of which works inside seatbelt
        excludedCommands = [ "pdf2md" ];
        # uv keeps managed pythons and tools in ~/.local/share/uv and writes
        # temp files there even for `uv run`
        filesystem.allowWrite = [
          "~/.cache/"
          "~/.local/share/uv/"
        ];
      };

      hooks.PostToolUse = [
        {
          matcher = "Edit|MultiEdit|Write|Bash";
          hooks = [
            {
              type = "command";
              # reload buffers when claude runs inside nvim's terminal
              command = ''[ -n "$NVIM" ] && nvim --server "$NVIM" --remote-send '<cmd>checktime<cr>' || true'';
            }
          ];
        }
      ];

      statusLine = {
        type = "command";
        command = "${root}/tools/claude_prompt.py";
      };

      enabledPlugins = {
        "github@claude-plugins-official" = true;
        "lua-lsp@claude-plugins-official" = true;
      };

      # notifications
      preferredNotifChannel = "notifications_disabled";
      inputNeededNotifEnabled = true;
      agentPushNotifEnabled = true;
      awaySummaryEnabled = false;

      # no co-authored-by trailer on commits or footer on prs
      attribution = {
        commit = "";
        pr = "";
      };

      # lessons go in claude.md files, skills, or config instead (see ./agents.md)
      autoMemoryEnabled = false;
      autoCompactEnabled = true;
      skipWorkflowUsageWarning = true;

      # nvim's default log dir isn't writable in the sandbox, so it falls
      # back to ./nvim.log in whatever directory it was run from
      env.NVIM_LOG_FILE = "/tmp/claude/nvim.log";
    };
  };

  # ~/.codex/config.toml is copied from this on each switch (see
  # home.activation.codexConfig) so codex can still record project trust
  programs.codex = {
    enable = true;
    settings = {
      model = "gpt-5.6-sol";
      model_reasoning_effort = "medium";
      service_tier = "default";
      features.js_repl = false;
      # leave the tab title to fish_title; with no items codex never sets one
      tui.terminal_title = [ ];

      # uv keeps managed pythons and tools in ~/.local/share/uv and writes to
      # its cache even for `uv run`
      default_permissions = "default";
      permissions =
        let
          uv = {
            "~/.cache/uv" = "write";
            "~/.local/share/uv" = "write";
          };
        in
        {
          default = {
            extends = ":workspace";
            filesystem = uv;
          };
          # read-only reviewers (skills/review/review.py) that can still run uv
          reviewer = {
            extends = ":read-only";
            filesystem = uv // {
              ":tmpdir" = "write";
              # the reviewed repo stays read-only even when it is under tmpdir
              ":workspace_roots"."." = "read";
            };
            network.enabled = true;
          };
        };
    };
  };

  home.file = {
    ".claude/CLAUDE.md".source = link "home/modules/agents.md";
    ".claude/skills".source = link "skills";
    # enter inserts a newline and ctrl+enter takes over enter's default
    # submit, which queues mid-turn instead of interrupting like sendNow
    ".claude/keybindings.json".text = builtins.toJSON {
      "$schema" = "https://www.schemastore.org/claude-code-keybindings.json";
      "$docs" = "https://code.claude.com/docs/en/keybindings";
      bindings = [
        {
          context = "Chat";
          bindings = {
            enter = "chat:newline";
            "ctrl+enter" = "chat:submit";
          };
        }
      ];
    };
    ".codex/AGENTS.md".source = link "home/modules/agents.md";
    # written as a real file by home.activation.codexConfig instead
    ".codex/config.toml".enable = false;
    ".codex/skills".source = link "skills";
  };

  # write the generated codex config as a mutable file, keeping the project
  # trust codex recorded since the last switch
  home.activation.codexConfig =
    let
      merge = pkgs.writeScript "merge-codex-config" ''
        #!${pkgs.python3}/bin/python3
        import sys, tomllib
        from pathlib import Path

        generated, dst = map(Path, sys.argv[1:])
        recorded = tomllib.loads(dst.read_text()).get("projects", {}) if dst.is_file() else {}
        tables = (f'[projects."{path}"]\ntrust_level = "{p["trust_level"]}"\n' for path, p in recorded.items())

        dst.unlink(missing_ok=True)
        dst.write_text("\n".join([generated.read_text(), *tables]))
      '';
    in
    lib.hm.dag.entryAfter [ "linkGeneration" ] ''
      run ${merge} ${config.home.file.".codex/config.toml".source} "$HOME/.codex/config.toml"
    '';
}
