# see `nixos-help`

{ pkgs, ... }:

{
  imports = [
    # generated by nixos-generate-config; copy from /etc/nixos/hardware-configuration.nix
    ./hardware.nix
    # ./nas.nix # TODO: fix this (currently breaks system)
  ];

  nixpkgs.hostPlatform = "x86_64-linux";

  # bootloader (don't touch these)
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.systemd-boot.enable = true;

  # networking
  networking.hostName = "fridge";
  networking.networkmanager.enable = true;

  # firewall
  networking.firewall = {
    enable = true;
    trustedInterfaces = [ "tailscale0" ]; # allow all traffic on tailscale
  };

  # tailscale
  services.tailscale = {
    enable = true;
    useRoutingFeatures = "both";
    extraSetFlags = [ "--ssh" ]; # enable tailscale ssh
  };
  # tailscale systray
  systemd.user.services.tailscale-systray = {
    description = "Tailscale systray application";
    wantedBy = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.tailscale}/bin/tailscale systray";
      Restart = "on-failure";
    };
  };

  # https://github.com/alipatti/bot (docker compose stack, cloned to ~/projects/bot)
  systemd.services.bot = {
    description = "alipatti-bot docker compose stack";
    wantedBy = [ "multi-user.target" ];
    after = [ "docker.service" ];
    requires = [ "docker.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      WorkingDirectory = "/home/ali/projects/bot";
      ExecStart = "${pkgs.docker}/bin/docker compose --env-file secrets.env up -d --build";
      ExecStop = "${pkgs.docker}/bin/docker compose --env-file secrets.env down";
      TimeoutStartSec = "20min"; # image build can take a while
    };
  };

  # TODO: setup nginx reverse proxy

  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";

  # graphics
  nixpkgs.config.allowUnfree = true; # allow non open source
  hardware.graphics.enable = true; # use hardware graphics card
  hardware.nvidia = {
    open = true; # recommended for Turing onwards
    powerManagement.enable = true; # fixes broken graphics after sleep
  };
  services.xserver.videoDrivers = [ "nvidia" ];

  # gdm/gnome
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;
  services.gnome.core-apps.enable = false;
  services.gnome.core-developer-tools.enable = false;
  services.gnome.games.enable = false;
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour
    gnome-user-docs
  ];

  # misc
  programs.nix-ld.enable = true; # needed for uv
  programs.fish.enable = true;
  virtualisation.docker.enable = true;
  programs.steam.enable = true;

  # packages
  environment.systemPackages = with pkgs; [
    # gui apps
    nautilus # files
    firefox # browser
    kitty # terminal
    prismlauncher
    spotify
    slack

    # cli tools (shared ones live in ../home)
    git-lfs
    nix-your-shell # use fish by default for nix-shell etc.
    trashy
    file
    wl-clipboard # clipboard support for tailscale systray

    # ai
    claude-code

    # language tooling
    gcc
    fnm

    # gnome extensions
    gnomeExtensions.appindicator # systray support for gnome
  ];

  users.users.ali = {
    isNormalUser = true;
    shell = pkgs.fish;
    extraGroups = [
      "networkmanager" # allow network config
      "wheel" # allow sudo
      "docker"
    ];
  };
  
  # env vars
  environment.sessionVariables = {
    BROWSER = "firefox";
  };

  # fonts
  fonts.packages = with pkgs; [
    nerd-fonts.cousine
  ];

  system.stateVersion = "25.11"; # don't change this line
}
