-- messages to the kitty watcher in tools/kitty_bridge.py. nvim writes them
-- to its own terminal as a user variable, so this also works over ssh, where
-- kitty's control socket can't be reached. fire and forget: no replies

local M = {}

-- generated by kitty.nix, and copied to remote hosts by `kitten ssh`
local SECRET_FILE = vim.fn.expand("~/.local/state/kitty-bridge-secret")

-- inside tmux the escape code would not reach kitty
M.available = vim.env.KITTY_WINDOW_ID ~= nil
	and vim.env.TMUX == nil
	and vim.fn.filereadable(SECRET_FILE) == 1

function M.send(message)
	local secret = vim.trim(vim.fn.readfile(SECRET_FILE)[1])
	local value = vim.base64.encode(vim.json.encode(vim.tbl_extend("error", message, { secret = secret })))
	vim.api.nvim_ui_send(("\27]1337;SetUserVar=kitty_bridge=%s\7"):format(value))
end

return M
