"""kitty watcher that lets nvim open and drive sibling windows, even over ssh.

nvim can't reach kitty's control socket from a remote host, but it can write
to its own terminal. so it sets a user variable (OSC 1337 SetUserVar) holding
a json message, and this watcher, loaded for every window via `watcher` in
kitty.conf, acts on it. see nvim/lua/kitty_bridge.lua.

anything printed to a terminal can set user vars, so messages carry a secret.
local nvims use one that never leaves this machine. `kitten ssh` copies a
second one to remote hosts, and it only opens windows on the host of the
window that sent it, so a leak there can't run anything here.

windows opened for a remote nvim run over nvim's ssh connection, through the
remote login shell (see login_shell in kitty.nix).
"""

import hmac
import json
import shlex
import sys
import time
from pathlib import Path
from typing import Any

from kittens.ssh.utils import (
    set_cwd_in_cmdline,
    set_env_in_cmdline,
    set_server_args_in_cmdline,
)
from kitty.boss import Boss
from kitty.constants import kitten_exe
from kitty.fast_data_types import add_timer
from kitty.window import Window

sys.path.insert(0, str(Path(__file__).parent))
from kitty_split import NARROW_WIDE_CUTOFF, tab_columns

USER_VAR = "kitty_bridge"
# generated by kitty.nix. remote hosts get the second one under the first's name
SECRET_FILE = Path.home() / ".local/state/kitty-bridge-secret"
REMOTE_SECRET_FILE = Path.home() / ".local/state/kitty-bridge-remote-secret"

# user vars that tag the windows nvim opens with their role and nvim's window
ROLE_VAR = "nvim_role"
PARENT_VAR = "nvim_parent"

POLL_SECONDS = 0.1
# paste anyway if a program hasn't asked for input after this long
STARTUP_TIMEOUT_SECONDS = 30
# fish drops input that arrives right after its first prompt
STARTUP_SETTLE_SECONDS = 0.3

# text for windows whose program hasn't started reading input yet, by window id
pending: dict[int, list[tuple[str, bool]]] = {}


def on_set_user_var(
    boss: Boss,
    window: Window,
    data: dict[str, Any],
) -> None:
    if data["key"] != USER_VAR or not data["value"]:
        return

    # keep the secret out of `kitten @ ls`
    window.user_vars.pop(USER_VAR)
    message = json.loads(data["value"])
    secret = message.pop("secret")
    remote = window.ssh_kitten_cmdline()
    if not (
        matches(secret, SECRET_FILE) or remote and matches(secret, REMOTE_SECRET_FILE)
    ):
        return

    match message["op"]:
        case "open":
            open_window(boss, window, remote, message)
        case "close":
            close_children(boss, window)
        case "focus":
            boss.set_active_window(
                int(message["window"]), switch_os_window_if_needed=True
            )


def on_close(
    boss: Boss,
    window: Window,
    data: dict[str, Any],
) -> None:
    """siblings also go when nvim's window closes without nvim saying so."""
    close_children(boss, window)


def matches(
    secret: str,
    path: Path,
) -> bool:
    expected = path.read_text().strip()
    return bool(expected) and hmac.compare_digest(secret, expected)


def open_window(
    boss: Boss,
    window: Window,
    remote: list[str],
    message: dict[str, Any],
) -> None:
    """focus or send text to the window for a role, launching it if needed."""
    show(boss, window)
    role, text, submit = (
        message["role"],
        message.get("text"),
        message.get("submit", False),
    )

    existing = next(
        (w for w in children(boss, window) if w.user_vars.get(ROLE_VAR) == role), None
    )
    if existing and text is None:
        boss.set_active_window(existing, switch_os_window_if_needed=True)
    elif existing:
        queue_paste(existing, text, submit)
    else:
        new = launch(boss, window, remote, message)
        pending[new.id] = [] if text is None else [(text, submit)]
        flush_when_ready(new)


def launch(
    boss: Boss,
    window: Window,
    remote: list[str],
    message: dict[str, Any],
) -> Window:
    args = [
        "launch",
        # nvim's tab, which needn't be the active one
        f"--match=id:{window.tabref().id}",
        "--type=window",
        "--location=last",
        f"--var={ROLE_VAR}={message['role']}",
        f"--var={PARENT_VAR}={window.id}",
    ]
    if message.get("text") is not None:
        args.append("--keep-focus")

    cmd = message.get("cmd") or []
    if remote:
        # the same `kitten ssh` as nvim's window, in nvim's directory
        argv = [kitten_exe(), *remote[1:]] if remote[0] == "kitten" else list(remote)
        set_cwd_in_cmdline(message["cwd"], argv)
        set_env_in_cmdline(message["env"], argv, clone=False)
        # ssh joins the remote command's words with spaces, so pass one
        # already-quoted string
        server_args = [shlex.join(cmd)] if cmd else []
        set_server_args_in_cmdline(server_args, argv, allocate_tty=bool(cmd))
        args += argv
    else:
        args += [f"--cwd={message['cwd']}"]
        args += [f"--env={k}={v}" for k, v in message["env"].items()]
        args += cmd

    return boss.window_id_map[int(boss.call_remote_control(window, tuple(args)))]


def queue_paste(
    window: Window,
    text: str,
    submit: bool,
) -> None:
    if window.id in pending:
        pending[window.id].append((text, submit))
    else:
        paste(window, text, submit)


def flush_when_ready(window: Window) -> None:
    """paste what's pending once the program reads input, which it signals by
    turning on bracketed paste."""
    deadline = time.monotonic() + STARTUP_TIMEOUT_SECONDS

    def flush(timer_id: int | None) -> None:
        for text, submit in pending.pop(window.id, []):
            paste(window, text, submit)

    def poll(timer_id: int | None) -> None:
        if window.destroyed:
            pending.pop(window.id, None)
        elif window.screen.in_bracketed_paste_mode or time.monotonic() > deadline:
            add_timer(flush, STARTUP_SETTLE_SECONDS, False)
        else:
            add_timer(poll, POLL_SECONDS, False)

    poll(None)


def paste(
    window: Window,
    text: str,
    submit: bool,
) -> None:
    # bracketed if the program asked for it, which keeps multiline text in
    # one piece; the enter that runs it has to come after
    window.paste_text(text)
    if submit:
        window.write_to_child("\r")


def show(
    boss: Boss,
    window: Window,
) -> None:
    """unzoom and pick tall or fat by the tab's width, like kitty_split.py."""
    ls = boss.call_remote_control(
        window, ("ls", f"--match-tab=id:{window.tabref().id}")
    )
    tab = json.loads(ls)[0]["tabs"][0]
    window.tabref().goto_layout(
        "fat" if tab_columns(tab) < NARROW_WIDE_CUTOFF else "tall"
    )


def children(
    boss: Boss,
    window: Window,
) -> list[Window]:
    parent = str(window.id)
    return [
        w for w in boss.window_id_map.values() if w.user_vars.get(PARENT_VAR) == parent
    ]


def close_children(
    boss: Boss,
    window: Window,
) -> None:
    for w in children(boss, window):
        boss.mark_window_for_close(w)
